name: scalableMARL
channels:
  - pytorch
dependencies:
  - python=3.8
  - pip
  - numpy
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch
  - wheel
  - h5py
  - typing-extensions
  - cython          #==0.29.0
  - numpy           #==1.19.0
  - psutil          ==5.8.0
  - tabulate        ==0.8.3
  - llvmlite
  - numba           #==0.52.0
  - cloudpickle     ==1.6.0
  - joblib          #==0.13.2
  - dill            ==0.3.3
  - scikit-learn    #==0.24.0
  - scipy           #==1.5.4
  - pandas          #==1.1.5
  - requests
  - lz4
  - pyyaml
  - mpi4py
  - tensorboard
  - seaborn
  - pillow
  - pip:
    - filterpy
    - opencv-python
    - librosa==0.4.2
    - tqdm==4.32.2
    - progressbar2==3.53.1
    - gym[atari]